name: Dependabot Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write

jobs:
  dependabot:
    name: Dependabot
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/dependabot.yml@ae08e7cb6c920790a5e093f83b778bb9735b2d65  # v0.2.7
    secrets:
      pr_approve_and_merge_pem: ${{ secrets.PR_APPROVE_AND_MERGE_PEM }}
