name: Dependabot Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write

jobs:
  dependabot:
    name: Dependabot
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/dependabot.yml@7ed8c49dde7d72864db8b10423592c85fc30df80  # v0.2.3
    secrets:
      pr_approve_and_merge_pem: ${{ secrets.PR_APPROVE_AND_MERGE_PEM }}
