name: Non-Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Main
    uses: ./.github/workflows/plan-and-apply.yml
    if: github.actor != 'osinfra-sa'
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Non-Production: Main"
      service_account: pt-techne-github@pt-corpus-tf61-nonprod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/pt-corpus-tf61-nonprod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=environments/non-production.tfvars
      opentofu_state_bucket: pt-techne-state-nonprod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-non-production
      workload_identity_provider: projects/640681940147/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
