name: Production
run-name: ${{ github.event.workflow_run.display_title || 'Production' }}

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Non-Production
    types:
      - completed
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  main:
    name: Main
    uses: ./.github/workflows/plan-and-apply.yml
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_commit.author.name != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      github_environment: "Production: Main"
      service_account: pt-techne-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      opentofu_kms_encryption_key: projects/pt-corpus-tf16-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_plan_args: -var-file=environments/production.tfvars
      opentofu_state_bucket: pt-techne-state-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: main-production
      working_directory: tests/plan-and-apply
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
